name: to_do_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  # Flavor 
  flavor: ^2.0.0

  # LocalDB
  hive_flutter: ^1.1.0

  # Page Route
  auto_route: ^7.8.4

  #Localization 
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:

  # Page Route
  auto_route_generator: ^7.3.2
  build_runner:

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true